name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Ensure using a compatible Node.js version

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install --legacy-peer-deps

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run tests
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application
        run: |
          echo "Deploying application..."
          ssh -o StrictHostKeyChecking=no root@37.27.47.155 << 'EOF'
            cd /root/Ghost
            git pull
            npm install -g yarn
            yarn install --legacy-peer-deps
            yarn build
            yarn start
            echo "Application deployed."
          EOF

