name: Build and Deploy

# Trigger this workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  # Build Job: Install dependencies
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

  # Test Job: Run placeholder tests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Run tests (placeholder for actual tests)
      - name: Run tests
        run: echo "Running placeholder tests... Tests completed."

  # Deploy Job: Deploy the application to the server
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to connect to the server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy the application
      - name: Deploy application
        run: |
          echo "Deploying application..."
          ssh -o StrictHostKeyChecking=no root@37.27.47.155 "cd /root/Ghost && git pull && npm install && npm start"
          echo "Application deployed."

