- name: Ensure monitoring systems are properly deployed
  hosts: monitoring
  become: yes

  tasks:
    - name: Install Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz
        mode: 0755

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt
        remote_src: yes

    - name: Copy Node Exporter binary to correct location
      copy:
        src: /opt/node_exporter-1.3.1.linux-amd64/node_exporter
        dest: /usr/local/bin/
        mode: 0755

    - name: Ensure Node Exporter Service is running
      systemd:
        name: node_exporter
        state: started
        enabled: yes

    - name: Check if Prometheus is running
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Check if Grafana is running
      systemd:
        name: grafana-server
        state: started
        enabled: yes

