version: '3.1'

services:
  db:
    image: arm64v8/mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

  ghost:
    image: arm64v8/ghost:latest
    restart: always
    depends_on:
      - db
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: example
      database__connection__database: ghost
    ports:
      - 2370:2368
    volumes:
      - ghost_content:/var/lib/ghost/content

volumes:
  db_data:
  ghost_content:

